safe: false
permalink: /posts/:title.html
exclude:
  - README.md

name: 精进之路
host: https://creatletter.github.io/creatwords.github.io/
desc: 只出一次错.

custom:
    category:
        default: 工作复盘
        another: 学习复盘
    categories:
      - name:  工作复盘
        title: Default Category

      - name:  学习复盘
        title: Another Category

    scrollingLoadCount: 2                          # 滚屏自动加载文章数量，“0”为关闭

meta:
    author:
        name: Wang Junjie
        email: jingmi_jie@outlook.com
        disqus: your-disqus-short-name              # Disqus缩略标识
        gcse: 000346898720731947188:13h55x32l0y     # Google自定义搜索标识ID
        github: your-github-account                 # GitHub账号
        gravatar: 1cd8c12591616d8c22aaa624f8c07834  # Gravatar头像标识

    disqus: disqus.com/embed.js                     # Disqus评论的JS地址
    gapi: http://www.google.com/jsapi               # Google API地址
    gravatar: http://en.gravatar.com/avatar/        # Gravatar头像服务器地址
